Updating back end settings
Currently running into issues with gulp

diff --git a/csfg b/csfg
--- a/csfg
+++ b/csfg
@@ -13,411 +13,386 @@
 #  - When 'start' is run open website in default browser without creating
 #    new terminal prompt.
 
-# Constants
+set -e
+
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
 
-# Print out help information
-function helpmenu {
-  printf "Script for performing tasks related to the CS Unplugged repository.\n\n"
-  printf "Usage: ./csu [COMMAND]\n"
-  printf "Replace [COMMAND] with a word from the list below.\n\n"
-  printf "COMMAND list:\n"
-  build_help
-  clean_help
-  printf "   dev [DEV_COMMAND] Run a developer command.\n"
-  end_help
-  printf "   help              View all help.\n"
-  restart_help
-  start_help
-  update_help
-  wipe_help
-  printf "\nDEV_COMMAND list:\n"
-  documentation_help
-  flush_help
-  logs_help
-  makemigrations_help
-  makeresources_help
-  migrate_help
-  shell_help
-  static_help
-  static_prod_help
-  style_help
-  test_suite_help
-  test_suite_backwards_help
-  test_coverage_help
-  test_specific_help
-  updatedata_help
+cmd_helps=()
+dev_cmd_helps=()
+
+defhelp() {
+  if [ "$1" = '-dev' ]; then
+    local command="${2?}"
+    local text="${3?}"
+    local help_str
+    help_str="$(printf '   %-18s %s' "$command" "$text")"
+    dev_cmd_helps+=("$help_str")
+  else
+    local command="${1?}"
+    local text="${2?}"
+    local help_str
+    help_str="$(printf '   %-18s %s' "$command" "$text")"
+    cmd_helps+=("$help_str")
+  fi
 }
+
+# Print out help information
+cmd_help() {
+  echo "Script for performing tasks related to the CS Field Guide repository."
+  echo
+  echo "Usage: ./csfg [COMMAND]"
+  echo "Replace [COMMAND] with a word from the list below."
+  echo
+  echo "COMMAND list:"
+  for str in "${cmd_helps[@]}"; do
+    echo -e "$str"
+  done
+  echo
+  echo "DEV_COMMAND list:"
+  for str in "${dev_cmd_helps[@]}"; do
+    echo -e "$str"
+  done
+}
+
+defhelp help 'View all help.'
+defhelp 'dev [DEV_COMMAND]' 'Run a developer command.'
 
 # Start development environment
-function start {
-  printf "Creating systems...\n"
+cmd_start() {
+  echo "Creating systems..."
   docker-compose up -d
-  printf "\n"
+  echo ""
   # Run helper functions
-  update
+  cmd_update
   # Alert user that system is ready
-  printf "\n${GREEN}Systems are ready!${NC}\n"
-  printf "Open your preferred web browser to the URL 'localhost'\n"
+  echo -e "\n${GREEN}Systems are ready!${NC}"
+  echo "Open your preferred web browser to the URL 'localhost'"
 }
-function start_help {
-  printf "   start             Start development environment (this also runs\n"
-  printf "                     the update command).\n"
-}
+
+defhelp start 'Start development environment (this also runs the update command).'
 
 # Stop development environment
-function end {
-  printf "Stopping systems... (takes roughly 10 to 20 seconds)\n"
+cmd_end() {
+  echo "Stopping systems... (takes roughly 10 to 20 seconds)"
   docker-compose down
-  printf "\nDeleting system volumes...\n"
-  docker volume ls -qf dangling=true | xargs -r docker volume rm
+  echo
+  echo "Deleting system volumes..."
+  volumes=($(docker volume ls -qf dangling=true ))
+  for volume in "${volumes[@]}"; do
+      docker volume rm "${volume}"
+  done
 }
-function end_help {
-  printf "   end               Stop development environment.\n"
-}
+defhelp end 'Stop development environment.'
 
-# Stop and then restart development environment
-function restart_help {
-  printf "   restart           Stop and then restart development environment.\n"
+cmd_restart() {
+  cmd_end
+  cmd_start
 }
+defhelp restart 'Stop and then restart development environment.'
 
 # Run Django migrate and updatedata commands
-function update {
-  static
+cmd_update() {
+  dev_static
 
-  printf "\n"
-  migrate
+  echo ""
+  dev_migrate
 
-  printf "\n"
-  updatedata
+  echo ""
+  dev_updatedata
 
-  static_scratch
-  collect_static
+  dev_static_scratch
+  echo ""
+  dev_makeresourcethumbnails
+  dev_collect_static
 }
-function update_help {
-  printf "   update            Run Django migrate and updatedata commands\n"
-  printf "                     and build static files.\n"
-}
-
-# Run Django flush command
-function flush {
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py flush
-}
-function flush_help {
-  printf "   flush             Run Django flush command.\n"
-}
-
-# Run Django makemigrations command
-function makemigrations {
-  printf "Creating database migrations...\n"
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py makemigrations
-}
-function makemigrations_help {
-  printf "   makemigrations    Run Django makemigrations command.\n"
-}
-
-# Run Django makeresources command
-function makeresources {
-  printf "Creating static resource PDFs...\n"
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py makeresources
-}
-function makeresources_help {
-  printf "   makeresources     Run Django makeresources command.\n"
-}
-
-# Run Django migrate command
-function migrate {
-  printf "Applying database migrations...\n"
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py migrate
-}
-function migrate_help {
-  printf "   migrate           Run Django migrate command.\n"
-}
-
-# Run Django updatedata command
-function updatedata {
-  printf "Loading chapters content...\n"
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py updatedata
-}
-function updatedata_help {
-  printf "   updatedata        Run updatedata command.\n"
-}
-
-# Build Docker images
-function build {
-  printf "Building Docker images...\n"
-  docker-compose build
-  printf "\nDeleting untagged images...\n"
-  docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
-}
-function build_help {
-  printf "   build             Build or rebuild Docker images.\n"
-}
-
-# Build static files
-function static {
-  printf "Building static files...\n"
-  docker-compose exec nginx gulp build
-}
-function static_help {
-  printf "   static            Build static files.\n"
-}
-
-# Build production static files
-function static_prod {
-  printf "Building production static files...\n"
-  docker-compose exec nginx gulp build --production
-}
-function static_prod_help {
-  printf "   static_prod       Build production static files.\n"
-}
-
-# Build scratch static files
-function static_scratch {
-  printf "Building scratch images...\n"
-  docker-compose exec nginx gulp scratch
-}
+defhelp update 'Run Django migrate and updatedata commands and build static files.'
 
 # Collecting static files
-function collect_static {
-  printf "\nCollecting static files..."
+dev_collect_static() {
+  echo
+  echo "Collecting static files..."
   docker-compose exec django /docker_venv/bin/python3 ./manage.py collectstatic --no-input --clear
 }
+defhelp -dev collect_static "Collecting static files."
+
+# Run Django flush command
+dev_flush() {
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py flush
+}
+defhelp -dev flush 'Run Django flush command.'
+
+# Run Django makemigrations command
+dev_makemigrations() {
+  echo "Creating database migrations..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py makemigrations
+}
+defhelp -dev makemigrations 'Run Django makemigrations command.'
+
+# Run Django makeresources command
+dev_makeresources() {
+  echo "Creating static resource PDFs..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py makeresources
+}
+defhelp -dev makeresources 'Run Django makeresources command.'
+
+# Run Django makeresourcethumbnails command
+dev_makeresourcethumbnails() {
+  echo "Creating thumbnails for resource PDFs..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py makeresourcethumbnails
+}
+defhelp -dev makeresourcethumbnails 'Run Django makeresourcethumbnails command.'
+
+
+# Run Django makemessages command
+dev_makemessages() {
+  echo "Creating message files..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py makemessages -l en
+}
+defhelp -dev makemessages 'Run Django makemessages command.'
+
+# Run Django compilemessages command
+dev_compilemessages() {
+  echo "Compiling message files..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py compilemessages
+}
+defhelp -dev compilemessages 'Run Django compilemessages command.'
+
+# Run Django migrate command
+dev_migrate() {
+  echo "Applying database migrations..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py migrate
+}
+defhelp -dev migrate 'Run Django migrate command.'
+
+# Run Django updatedata command
+dev_updatedata() {
+  echo "Loading content..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py updatedata
+}
+defhelp -dev updatedata 'Run updatedata command.'
+
+# Build Docker images
+dev_build() {
+  echo "Building Docker images..."
+  docker-compose build
+  echo
+  echo "Deleting untagged images..."
+  untagged_images=($(docker images --no-trunc | grep '<none>' | awk '{print $3}'))
+  if [[ ${#untagged_images[@]} -gt 0 ]]; then
+      docker rmi "${untagged_images[@]}"
+  fi
+}
+defhelp -dev build 'Build or rebuild Docker images.'
+
+# Build static files
+dev_static() {
+  echo "Building static files..."
+  docker-compose exec nginx gulp build
+}
+defhelp -dev static 'Build static files.'
+
+# Build production static files
+dev_static_prod() {
+  echo "Building production static files..."
+  docker-compose exec nginx gulp build --production
+}
+defhelp -dev static_prod 'Build production static files.'
+
+# Build scratch static files
+dev_static_scratch() {
+  echo "Building scratch images..."
+  docker-compose exec nginx gulp scratch
+}
+defhelp -dev static_scratch "Build scratch images."
 
 # Run shell
-function shell {
+dev_shell() {
   docker-compose exec django bash
 }
-function shell_help {
-  printf "   shell             Open shell to Django folder.\n"
+defhelp -dev shell "Open shell to Django folder."
+
+# Reboot Django Docker container
+dev_reboot_django() {
+  echo "Rebooting Django Docker container..."
+  docker-compose restart django
 }
+defhelp -dev reboot_django 'Reboot Django Docker container.'
 
 # Run style checks
-function style {
-  printf "Running PEP8 style checker...\n"
+dev_style() {
+  echo "Running PEP8 style checker..."
   docker-compose exec django /docker_venv/bin/flake8
   pep8_status=$?
-  printf "\nRunning Python docstring checker...\n"
+  echo
+  echo "Running Python docstring checker..."
   docker-compose exec django /docker_venv/bin/pydocstyle --count --explain
   pydocstyle_status=$?
-  ! (( $pep8_status || $pydocstyle_status ))
+  ! (( pep8_status || pydocstyle_status ))
 }
-function style_help {
-  printf "   style             Run style checks.\n"
-}
+defhelp -dev style 'Run style checks.'
 
 # Run test suite
-function test_suite {
-  printf "Running test suite...\n"
-  docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-field-guide/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3
+dev_test_suite() {
+  echo "Running test suite..."
+  if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then
+    docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-field-guide/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3
+  else
+    docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-field-guide/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --nomigrations
+  fi
 }
-function test_suite_help {
-  printf "   test              Run test suite with code coverage.\n"
-}
+defhelp -dev test_suite 'Run test suite with code coverage.'
 
 # Run specific test suite
-function test_specific {
-  printf "Running specific test suite...\n"
-  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing "${1}" -v 3
+dev_test_specific() {
+  echo "Running specific test suite..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing "${1}" -v 3 --nomigrations
 }
-function test_specific_help {
-  printf "   test_specific     Run specific test suite. Pass in parameter\n"
-  printf "                     of Python test module.\n"
-}
+defhelp -dev test_specific 'Run specific test suite. Pass in parameter of Python test module.'
 
 # Display test coverage table
-function test_coverage {
-  printf "Displaying test suite coverage...\n"
+dev_test_coverage() {
+  echo "Displaying test suite coverage..."
   docker-compose exec django /docker_venv/bin/coverage xml -i
   docker-compose exec django /docker_venv/bin/coverage report -m --skip-covered
 }
-function test_coverage_help {
-  printf "   test_coverage     Display code coverage report.\n"
-}
+defhelp -dev test_coverage 'Display code coverage report.'
 
 # Run test suite backwards for CI testing
-function test_suite_backwards {
-  printf "Running test suite backwards...\n"
-  if [ "$TRAVIS_PULL_REQUEST" != "false" ]
-  then
-    docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing --pattern "test_*.py" --reverse -v 0
-  fi
+dev_test_backwards() {
+  echo "Running test suite backwards..."
+  docker-compose exec django /docker_venv/bin/python3 ./manage.py test --settings=config.settings.testing --pattern "test_*.py" --reverse -v 0
 }
-function test_suite_backwards_help {
-  printf "   test_backwards    Run test suite backwards.\n"
-}
+defhelp -dev test_backwards 'Run test suite backwards.'
 
 # Generates the documentation (with warnings as errors)
-function documentation {
-  printf "Removing any existing documentation...\n"
+dev_docs() {
+  echo "Removing any existing documentation..."
   docker-compose exec django rm -rf /cs-field-guide/docs/build/
   docker-compose exec django mkdir /cs-field-guide/docs/build/
-  printf "\nCreating documentation...\n"
+  echo
+  echo "Creating documentation..."
   docker-compose exec django /docker_venv/bin/sphinx-build -W /cs-field-guide/docs/source/ /cs-field-guide/docs/build/
 }
-function documentation_help {
-  printf "   docs              Generate documentation.\n"
-}
+defhelp -dev docs 'Generate documentation.'
 
 # Delete all untagged dangling Docker images
-function clean {
-  printf "If the following commands return an argument not found error,\n"
-  printf "this is because there is nothing to delete for clean up.\n"
+cmd_clean() {
+  echo "If the following commands return an argument not found error,"
+  echo "this is because there is nothing to delete for clean up."
 
-  printf "\nDeleting unused volumes...\n"
-  docker volume ls -qf dangling=true | xargs -r docker volume rm
-  printf "\nDeleting exited containers...\n"
-  docker ps --filter status=dead --filter status=exited -aq | xargs docker rm -v
-  printf "\nDeleting dangling images...\n"
-  docker rmi $(docker images -f "dangling=true" -q)
+  echo
+  echo "Deleting unused volumes..."
+
+  unused_volumes=($(docker volume ls -qf dangling=true))
+  for vol in "${unused_volumes[@]}"; do
+      docker volume rm "${vol}"
+  done
+
+  echo
+  echo "Deleting exited containers..."
+  exited_containers=($(docker ps --filter status=dead --filter status=exited -aq))
+  for container in "${exited_containers[@]}"; do
+      docker rm -v "${container}"
+  done
+  echo
+  echo "Deleting dangling images..."
+  dangling_images=($(docker images -f "dangling=true" -q))
+  if [[ ${#dangling_images[@]} -gt 0 ]]; then
+      docker rmi "${dangling_images[@]}"
+  fi
 }
-function clean_help {
-  printf "   clean             Delete unused Docker files.\n"
-}
+defhelp clean 'Delete unused Docker files.'
 
 # Delete all Docker containers and images
-function wipe {
-  docker rm $(docker ps -a -q)
-  docker rmi $(docker images -q)
+cmd_wipe() {
+  docker ps -a -q | xargs docker rm
+  docker images -q | xargs docker rmi
 }
-function wipe_help {
-  printf "   wipe              Delete all Docker containers and images.\n"
-}
+defhelp wipe 'Delete all Docker containers and images.'
 
 # View logs
-function logs {
+cmd_logs() {
   docker-compose logs
 }
-function logs_help {
-  printf "   logs              View logs.\n"
+defhelp logs 'View logs.'
+
+ci_test_general() {
+  docker-compose exec django /docker_venv/bin/coverage run --rcfile=/cs-field-guide/.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --exclude-tag=resource --exclude-tag=management
+  test_status=$?
+  dev_test_coverage
+  coverage_status=$?
+  bash <(curl -s https://codecov.io/bash)
+  ! (( $test_status || $coverage_status ))
 }
 
-function process_dev_command() {
-  if [ $# -lt 1 ]
-  then
-    printf "${RED}ERROR: dev command requires one parameter!${NC}\n"
-    helpmenu
+ci_style() {
+  dev_style
+}
+
+ci_test_backwards() {
+  dev_test_backwards
+}
+
+ci_docs() {
+  dev_docs
+}
+
+cmd_ci() {
+  cmd_start
+  local cmd="$1"
+  shift
+  if [ -z "$cmd" ]; then
+    echo -e "${RED}ERROR: ci command requires one parameter!${NC}"
+    cmd_help
     exit 1
+  fi
+  if silent type "ci_$cmd"; then
+    "ci_$cmd" "$@"
+    exit $?
   else
-    case "$1" in
-      docs)
-        documentation
-        exit
-        ;;
-      flush)
-        flush
-        exit
-        ;;
-      logs)
-        logs
-        exit
-        ;;
-      makeresources)
-        makeresources
-        exit
-        ;;
-      makemigrations)
-        makemigrations
-        exit
-        ;;
-      migrate)
-        migrate
-        exit
-        ;;
-      shell)
-        shell
-        exit
-        ;;
-      static)
-        static
-        static_scratch
-        collect_static
-        exit
-        ;;
-      static_prod)
-        static_prod
-        static_scratch
-        collect_static
-        exit
-        ;;
-      style)
-        style
-        exit
-        ;;
-      test)
-        test_suite
-        exit
-        ;;
-      test_backwards)
-        test_suite_backwards
-        exit
-        ;;
-      test_coverage)
-        test_coverage
-        exit
-        ;;
-      test_specific)
-        test_specific $2
-        exit
-        ;;
-      updatedata)
-        updatedata
-        exit
-        ;;
-    esac
+    echo -e "${RED}ERROR: Unknown command!${NC}"
+    echo "Type './csfg help' for available commands."
+    return 1
   fi
 }
 
+silent() {
+  "$@" > /dev/null 2>&1
+}
+
+cmd_dev() {
+  local cmd="$1"
+  shift
+  if [ -z "$cmd" ]; then
+    echo -e "${RED}ERROR: dev command requires one parameter!${NC}"
+    cmd_help
+    return 1
+  fi
+  if silent type "dev_$cmd"; then
+    "dev_$cmd" "$@"
+    exit $?
+  else
+    echo -e "${RED}ERROR: Unknown command!${NC}"
+    echo "Type './csfg help' for available commands."
+    return 1
+  fi
+}
 
 # If no command given
-if [ $# -eq 0 ]
-then
-  printf "${RED}ERROR: This script requires a command!${NC}\n"
-  helpmenu
+if [ $# -eq 0 ]; then
+  echo -e "${RED}ERROR: This script requires a command!${NC}"
+  cmd_help
   exit 1
 fi
-case "$1" in
-  build)
-    build
-    exit
-    ;;
-  clean)
-    clean
-    exit
-    ;;
-  dev)
-    process_dev_command $2 $3
-    ;;
-  end)
-    end
-    exit
-    ;;
-  help)
-    helpmenu
-    exit
-    ;;
-  restart)
-    end
-    start
-    exit
-    ;;
-  start)
-    start
-    exit
-    ;;
-  update)
-    update
-    exit
-    ;;
-  wipe)
-    wipe
-    exit
-    ;;
-esac
-
-# If no command triggered
-printf "${RED}ERROR: Unknown command!${NC}\n"
-printf "Type './csu help' for available commands.\n"
-exit 1
+cmd="$1"
+shift
+if silent type "cmd_$cmd"; then
+  "cmd_$cmd" "$@"
+  exit $?
+else
+  echo -e "${RED}ERROR: Unknown command!${NC}"
+  echo "Type './csfg help' for available commands."
+  exit 1
+fi
